import os
import json
from google import genai
from dotenv import load_dotenv
from soh_model import predict

load_dotenv()
#genai.configure(api_key=os.getenv("GEMINI_AI_KEY"))
client = genai.Client()

def ask_gemini(input):
    #first ask if the query is a prediction request
    #if so ask again to return a JSON list if the 21 values
    #then ask gemini to out an answer using the value generated by our model
    try:
        #model = genai.GenerativeModel("gemini-1.5-flash")

        #identify intention
        question = f"""You are an intent classifier.
        The user asked:
        "{input}"

        Respond with EXACTLY ONE WORD:

        PREDICT  - if the user wants a battery SOH prediction.
        GENERAL  - otherwise.
        """

        response = client.models.generate_content(model="gemini-2.5-flash", contents=question)
        intent = response.text.strip().upper()

        #if not a prediction request, just answer
        if intent != "PREDICT":
            output = client.models.generate_content(model="gemini-2.5-flash", contents=input)
            return output.text

        #if it is a prediction request
        question = f"""
        Retrieve exactly 21 battery cell voltages from the message below:

        "{input}"

        Return them ONLY as a JSON array like:
        [4.01, 3.56, 3.47, ... 21 numbers ...]

        If not exactly 21 numbers exist, return "INVALID"
        """
        battery_array = client.models.generate_content(model="gemini-2.5-flash", contents=question)
        extracted_text = battery_array.text.strip()

        #if not all 21 value return
        if extracted_text == "INVALID":
            return "To predict SOH, please provide exactly 21 voltage values."
        
        extracted_text = extracted_text.replace("```json", "").replace("```", "").strip()
        
        #attempt to turn gemini answer to array
        try:
            battery_array = json.loads(extracted_text)
        except:
            return "Could not parse voltages. Please provide 21 numeric values."

        if len(battery_array) != 21:
            return f"Exactly 21 voltages required. You provided {len(battery_array)}."
        
        #predict SOH with battery cell data
        result = predict(battery_array)
        print("model prediction" + str(result))
        result = (result - int(result))*100
        question = f"""
        You are replying to a user request for predicting battery SOH.
        The ML model's prediction is: {result}%.

        User question:
        "{input}"

        Generate a helpful explanation of what this SOH value means.
        """
        prediction = client.models.generate_content(model="gemini-2.5-flash", contents=question)
        return prediction.text
    except Exception as e:
        return f"Gemini API Error: {str(e)}"
